### ISSUE TITLE
按照README配置android不成功？

### ISSUE THREAD

**Issue by dongweb** [reactnativecn/react-native-http-cache#12]
您好，完全是按照README配置的android，却并不能成功运行。抛出这种形式的错误呢？能帮忙看下什么问题不？
Warning: /Users/dd_fly/fangge_android/android/app/src/main/AndroidManifest.xml:14:5-80 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:14:5-80 duplicated with element declared at AndroidManifest.xml:10:5-80
/Users/dd_fly/fangge_android/android/app/src/main/AndroidManifest.xml:14:5-80 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:14:5-80 duplicated with element declared at AndroidManifest.xml:10:5-80
:app:processDebugResources
:app:generateDebugSources
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/dd_fly/fangge_android/android/app/src/main/java/com/veryside/MainActivity.java:13: 错误: 找不到符号
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  符号:   类 Bundle
  位置: 类 MainActivity
/Users/dd_fly/fangge_android/android/app/src/main/java/com/veryside/MainActivity.java:14: 错误: 找不到符号
        mReactInstanceManager = ReactInstanceManager.builder()
        ^
  符号:   变量 mReactInstanceManager
  位置: 类 MainActivity
/Users/dd_fly/fangge_android/android/app/src/main/java/com/veryside/MainActivity.java:21: 错误: 找不到符号
            .setInitialLifecycleState(LifecycleState.RESUMED)
                                      ^
  符号:   变量 LifecycleState
  位置: 类 MainActivity
/Users/dd_fly/fangge_android/android/app/src/main/java/com/veryside/MainActivity.java:18: 错误: 找不到符号
            .addPackage(new MainReactPackage())
                            ^
  符号:   类 MainReactPackage
  位置: 类 MainActivity
/Users/dd_fly/fangge_android/android/app/src/main/java/com/veryside/MainActivity.java:14: 错误: 找不到符号
        mReactInstanceManager = ReactInstanceManager.builder()
                                ^
  符号:   变量 ReactInstanceManager
  位置: 类 MainActivity
5 个错误
:app:compileDebugJavaWithJavac FAILED

**Comment by sunnylqm** [comment]
从0.29版本开始应该是在mainapplication而不是mainactivity中修改了，文档还没做相应的修改

**Comment by dongweb** [comment]
@sunnylqm 确实如你所说。谢了。
