### ISSUE TITLE
[react native 0.29.0]Could not invoke RCTHttpCache.getHttpCacheSize

### ISSUE THREAD

**Issue by yolinsoft** [reactnativecn/react-native-http-cache#3]
[react native 0.29.0]Could not invoke RCTHttpCache.getHttpCacheSize

**Comment by tdzl2003** [comment]
Duplicated as #2 , this module should be updated for RN 0.27+

**Comment by Lepinr** [comment]
+1
rn版本都到0.31了...

**Comment by alexlipe** [comment]
@yolinsoft 在0.28下 安卓获取不到缓存大小, 但是clear 清除时,可以清除掉缓存...
