### ISSUE TITLE
cannot read property 'clearCache' of undefined

### ISSUE THREAD

**Issue by pheromone** [reactnativecn/react-native-http-cache#36]
only iOS,android is work.
xcode can run,but react-native run-ios can not run.
error:  cannot read property 'clearCache' of undefined

**Comment by hqwlkj** [comment]
将package.json 中的：
`"react-native-http-cache": "^0.2.0`
修改为：
`"react-native-http-cache": "https://github.com/puti94/react-native-http-cache"`
就好了

**Comment by TommyLeong** [comment]
@hqwlkj I did exactly what you said, but I'm still facing this issue. Is this library no longer supported? 😢

**Comment by hqwlkj** [comment]
@TommyLeong 
Please refer to the instruction manual of the project.    
[react-native-http-cache](https://github.com/puti94/react-native-http-cache)

**Comment by TommyLeong** [comment]
@hqwlkj I did exactly mentioned in the manual, but I result in getting 'React/RCTImageLoader.h' file not found. 

In the case where I do not link and append the .a file, I'll get cannot read property 'clearCache' of undefined.

**Comment by hqwlkj** [comment]
@TommyLeong  

Have you tested using the master [react-native-http-cache](https://github.com/reactnativecn/react-native-http-cache) molecule file? Is there the same problem?

**Comment by TommyLeong** [comment]
Not sure what was being cached earlier, tried using `npx react-native-clean-project` and I'm able to use the module now. 

End up using ```react-native-http-cache": "^0.2.0``` and follow the [instruction given](http://facebook.github.io/react-native/docs/linking-libraries-ios.html). Everything is working fine again. 
```
react-native-cli: 2.0.1
react-native: 0.60.0
```

**Comment by houzhanshan** [comment]
@hqwlkj I've tried to integrate with new project,xcode can run,but react-native run-ios can not run.
error: cannot read property 'clearCache' of undefined,I've link libRCTHttpCache.a, app open failed

**Comment by ss2012** [comment]
> Not sure what was being cached earlier, tried using `npx react-native-clean-project` and I'm able to use the module now.
> 
> End up using `react-native-http-cache": "^0.2.0` and follow the [instruction given](http://facebook.github.io/react-native/docs/linking-libraries-ios.html). Everything is working fine again.
> 
> ```
> react-native-cli: 2.0.1
> react-native: 0.60.0
> ```



> Not sure what was being cached earlier, tried using `npx react-native-clean-project` and I'm able to use the module now.
> 
> End up using `react-native-http-cache": "^0.2.0` and follow the [instruction given](http://facebook.github.io/react-native/docs/linking-libraries-ios.html). Everything is working fine again.
> 
> ```
> react-native-cli: 2.0.1
> react-native: 0.60.0
> ```



> 不知道之前缓存了什么，请尝试使用`npx react-native-clean-project`，现在可以使用该模块了。
> 
> 最终使用`react-native-http-cache": "^0.2.0`并按照[给出](http://facebook.github.io/react-native/docs/linking-libraries-ios.html)的[说明进行操作](http://facebook.github.io/react-native/docs/linking-libraries-ios.html)。一切恢复正常。
> 
> ```
> react-native-cli: 2.0.1
> react-native: 0.60.0
> ```

我的问题和你一模一样，pod库没有，然后手动添加库，提示'React/RCTDefines.h' file not found，你最终是怎么解决的呢

**Comment by ss2012** [comment]
> @hqwlkj我尝试与新项目集成，结果是相同的。
> 
> 重现步骤：
> 
> 1. React-native初始projectName
> 2. 附加`"react-native-http-cache": "^0.2.0"`在package.json中并执行yarn安装
> 3. 转到node_module，将RCTHttpCache.xcodeproj拖放到Libraries文件夹中
> 4. 拖放libRCTHttpCache.a以使用库构建阶段的链接二进制文件
> 5. 建立项目
> 6. 生成失败并出现错误
> 
> ```
> /react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found
> ```
> 
> 附加：
> 如果我使用`react-native-http-cache": "https://github.com/puti94/react-native-http-cache`
> 该错误将改为以下内容：
> 
> ```
> TypeError: Cannot read property 'clearCache' of undefined
> ```

操作和你一样，问题也是和你一样，手动添加库提示/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found，你最终是怎么解决的呢

**Comment by chengxiaofeng123** [comment]
你这个问题解决了吗
